name: flutter_app
description: "A new Flutter project with Clean Architecture"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  shadcn_ui: ^0.19.3
  flashy_tab_bar2: ^0.0.10
  adaptive_theme: ^3.6.0


  # Sign in
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3

  # State Management
  flutter_bloc: ^9.1.0
  #bloc: ^9.0.0
  get: ^4.6.6
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.7

  # Firebase
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0

  # Utils
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  package_info_plus: ^8.1.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5
  path_provider: ^2.1.5

  # Analytics
  posthog_flutter: 4.8.0
  heap_flutter_bridge: ^0.1.3
  flutter_branch_sdk: ^8.3.1

  # Push Notifications
  onesignal_flutter: ^5.2.9

  # Translations
  azbox: ^1.0.5

  # Onboarding
  introduction_screen: ^3.1.14

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

 # bloc_test: ^9.1.5
  mockito: ^5.4.4
  build_runner: ^2.4.8

  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/launcher/

